use super::*;

pub struct Fdb__Vec_Index {}

impl Fdb__Vec_Index {
    /*
    println!("hello from rust");

    use fastembed::{EmbeddingModel, InitOptions, TextEmbedding};

    // With default options
    let mut model = TextEmbedding::try_new(Default::default()).unwrap();

    // With custom options
    let mut model = TextEmbedding::try_new(
        InitOptions::new(EmbeddingModel::AllMiniLML6V2).with_show_download_progress(true),
    )
    .unwrap();

    let documents = vec![
        "passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! ",
        "passage: , World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! ",
        "passage: ! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! ",
        "food: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! ",
        "other: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! ",
        "more: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! ",
        "2info: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! passage: Hello, World! ",
    ];

    // Generate embeddings with the default batch size, 256
    let t0 = std::time::Instant::now();
    let embeddings = model.embed(documents, None).unwrap();
    let t1 = std::time::Instant::now();

    println!("total embedding time; {:?}", t1 - t0);

    println!("Embeddings length: {}", embeddings.len()); // -> Embeddings length: 4
    println!("Embedding dimension: {}", embeddings[0].len()); // -> Embedding dimension: 384

     */
}
